language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: 5379b756b43c077ae2382a02111f34e5661427838ac3c273de5d73bcb93377e6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" -a \"$TRAVIS_PHP_VERSION\" != \"7\" ]; then curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports; fi"
